---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: true
platforms:
  - name: lab-lab
    vm_os_id: /subscriptions/9bd05406-c85b-4e5d-9b66-c8920883291a/resourceGroups/RG-weu-compute-image-gallery/providers/Microsoft.Compute/galleries/ComputeImageGallery/images/ubuntu-20-04
    remote_ports:
      - 80
      - 8080
      - 443
      - 8443
  - name: treta-treta
    vm_os_id: /subscriptions/9bd05406-c85b-4e5d-9b66-c8920883291a/resourceGroups/RG-weu-compute-image-gallery/providers/Microsoft.Compute/galleries/ComputeImageGallery/images/ubuntu-20-04
    remote_ports:
      - 80
      - 8080
      - 443
      - 8443

lint: |
  set -e
  yamllint .
  ansible-lint

provisioner:
  name: ansible
verifier:
  name: ansible

backend_config_key: "terraform-lab.tfstate"
backend_config_storage_account_name: "computeprodstorage"
backend_config_container_name: "grafana-preprod"
backend_config_access_key: "emuAUM/lezcHGXrgfCsgdcvtj8+MZYjTioHKPQ319Oy2pROxHjanK6w6yVV61C9OievgKjDBfVkHMVzm/LXEog=="

resource_group_name: molecule_delegated
location: westeurope
private_keypair_path: "/Users/victor/.ssh/id_rsa"
azure_tags: 
  deployer: santosv
  application: molecule
  stage: test

admin_password: abd8b257177ce7f1cf1d2a01
admin_username: azureuser
boot_diagnostics: "yes"
custom_data: ""
enable_ssh_key: "true"
extra_ssh_keys:
  - ~/.ssh/id_rsa.pub
identity_type: SystemAssigned
license_type: "null"
location_alt: westeurope
nb_data_disk: "0"
private_ip_address_allocation: Static
subnet: /subscriptions/9bd05406-c85b-4e5d-9b66-c8920883291a/resourceGroups/RG-WEU-vnet-tomtom-default/providers/Microsoft.Network/virtualNetworks/VNET-tomtom-default/subnets/SN-tomtom-default
vm_size: Standard_D4s_v3